software-deployment-method:
  - conda
conda-prefix: /home/mjhk/.snakemake/envs/smk_wgs
scheduler: greedy
printshellcmds: True
keep-incomplete: True
cores: 80
resources:
  mem_mb: 200000  # 200GB
default-resources:
  mem_mb: 5000  # 5GB
set-threads:
  fastp: 4
  fastqc: 4
  bwamem2: 10
  manta: 10
  tiddit: 10
  wham: 10
  gridss: 10
  svaba: 10
  mutect2: 10
  duphold: 5
  vep: 5
  annovar: 5
  filter_annotations: 20
set-resources:
  mark_duplicates:
    mem_mb: 100000  # 100GB
  base_recalibrator:
    mem_mb: 50000  # 50GB
  apply_bqsr:
    mem_mb: 50000  # 50GB
  gridss:
    mem_mb: 50000  # 50GB
    mem_mb_other: 10000  # 10GB
  snpeff:
    mem_mb: 50000  # 50GB
  mutect2:
    mem_mb: 10000  # 10GB
  learn_read_orientation_model:
    mem_mb: 10000  # 10GB
  get_pileup_summaries:
    mem_mb: 10000  # 10GB
  calculate_contamination:
    mem_mb: 10000  # 10GB
  filter_mutect_calls:
    mem_mb: 10000  # 10GB
